server:
  port: 8068

spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  data:
    redis:
      host: 127.0.0.1
      password: YourStrongPassword
      port: 6379

short-link:
  domain:
    default: 127.0.0.1:8068
    # default: go.chanler.dev
  shortcode:
    segmentStep: 10000
    prefetchRatio: 0.2
    a: 1234567
    b: 123456789
    length: 6
  rate-limit:
    create:
      enable: true
      rps: 500
      # 毫秒
      timeout: 20
    redirect:
      enable: true
      rps: 1000
      timeout: 5
    stats:
      enable: true
      rps: 100
      timeout: 50
  group:
    max-num: 20
  flow-limit:
    enable: true
    time-window: 5
    max-access-count: 5
  stats:
    locale:
      provider: local
      local:
        dbPath: ip2region.xdb
      amap:
        key:
        endpoint: https://restapi.amap.com/v3/ip
        timeout: 1000
  goto-domain:
    white-list:
      enable: true
      names: 'Chanler个人站,知乎,掘金,博客园,b站,GitHub,CSDN,微信,QQ,头条,微博,豆瓣,简书'
      details:
        - chanler.dev
        - zhihu.com
        - juejin.cn
        - cnblogs.com
        - bilibili.com
        - github.com
        - csdn.net
        - weixin.qq.com
        - qq.com
        - toutiao.com
        - weibo.com
        - douban.com
        - jianshu.com