server:
  port: 8001

spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: TheBestWorkLoanapp1
  mvc:
    view:
      prefix: /templates/
      suffix: .html

short-link:
  domain:
    default: chlr.cc
  stats:
    locale:
      provider: local
      local:
        dbPath: classpath:ip2region.xdb
      amap:
        key:
        endpoint: https://restapi.amap.com/v3/ip
        timeout: 1000
  goto-domain:
    white-list:
      enable: true
      names: 'Chanler个人站,知乎,掘金,博客园,b站,GitHub,CSDN,微信,QQ,头条,微博,豆瓣,简书'
      details:
        - chanler.dev
        - zhihu.com
        - juejin.cn
        - cnblogs.com
        - bilibili.com
        - github.com
        - csdn.net
        - weixin.qq.com
        - qq.com
        - toutiao.com
        - weibo.com
        - douban.com
        - jianshu.com